# Generated by Django 2.1.5 on 2019-02-26 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('biography', models.TextField()),
                ('style', models.CharField(max_length=50)),
                ('location', models.IntegerField()),
                ('experience', models.TextField()),
                ('playingTime', models.IntegerField()),
                ('type', models.IntegerField()),
            ],
        ),
    ]
